version: '3.3'
services:
  teslapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TESLAPI_KEY: vE7U7d5aUKXrd2nGCgE
      TESLAPI_USERNAME: teslapi
      TESLAPI_PASSWORD: 2jJm!ohvh#So
      TESLAPI_PORT: 8080
      TESLAPI_STORAGE_PATH: /go/src/github.com/teslapi/teslapi/storage/TeslaUSB
    ports:
      - 8080:8080
    volumes:
      - ./storage/:/go/src/github.com/teslapi/teslapi/storage
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 9001:9000
    command: ["server", "/data"]
